# DOCKER COMPOSE
#
version: "2.0"

services: 
  mysql_server:
    image: mysql
    environment: 
      - MYSQL_DATABASE=dapi_assg_db
      - MYSQL_USER=dan
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
    container_name: dapi_assg_mysql
  app:
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    image: nidhey27/docker-assign:1.0
    ports: 
      - 3000:3000
    environment: 
      - MYSQL_DATABASE=dapi_assg_db
      - MYSQL_USER=dan
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_HOST=dapi_assg_mysql
    depends_on: 
      - mysql_server
